# A first workflow to play around with the editor
name: GHA Cookbook first workflow

on:
  push:
    branches:
      -main
  workflow_dispatch:

jobs:
  first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}."
          echo "My secret is ${{ secrets.MY_SECRET }}."
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - run: tree  
